// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using gozba_na_klik.Data;

#nullable disable

namespace gozba_na_klik.Migrations
{
    [DbContext(typeof(GozbaDbContext))]
    [Migration("20251022100356_AddIsSuspendedToUser")]
    partial class AddIsSuspendedToUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("gozba_na_klik.Model.Entities.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("HouseNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("gozba_na_klik.Model.Entities.Allergen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Allergens");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Gluten"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Peanuts"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Lactose"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Eggs"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Soy"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Nuts"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Fish"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Shellfish"
                        });
                });

            modelBuilder.Entity("gozba_na_klik.Model.Entities.Restaurant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Capacity")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer");

                    b.Property<string>("Phone")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Photo")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Restaurants");
                });

            modelBuilder.Entity("gozba_na_klik.Model.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("character varying(35)");

                    b.Property<bool>("IsSuspended")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("character varying(35)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProfilePicture")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin1@gozba.com",
                            FirstName = "Admin",
                            IsSuspended = false,
                            LastName = "One",
                            PasswordHash = "$2a$12$97Po1ExL9B3PTNSyDYBlmetfcdxQNuLWdRQ06l.A8eC0pJ9s6Zee2",
                            Role = "Admin",
                            Username = "Admin1"
                        },
                        new
                        {
                            Id = 2,
                            Email = "admin2@gozba.com",
                            FirstName = "Admin",
                            IsSuspended = false,
                            LastName = "Two",
                            PasswordHash = "$2a$12$97Po1ExL9B3PTNSyDYBlmetfcdxQNuLWdRQ06l.A8eC0pJ9s6Zee2",
                            Role = "Admin",
                            Username = "Admin2"
                        },
                        new
                        {
                            Id = 3,
                            Email = "admin3@gozba.com",
                            FirstName = "Admin",
                            IsSuspended = false,
                            LastName = "Three",
                            PasswordHash = "$2a$12$97Po1ExL9B3PTNSyDYBlmetfcdxQNuLWdRQ06l.A8eC0pJ9s6Zee2",
                            Role = "Admin",
                            Username = "Admin3"
                        });
                });

            modelBuilder.Entity("gozba_na_klik.Model.Entities.UserAllergen", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("AllergenId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "AllergenId");

                    b.HasIndex("AllergenId");

                    b.ToTable("UserAllergens");
                });

            modelBuilder.Entity("gozba_na_klik.Model.Entities.WorkTime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("End")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("Start")
                        .HasColumnType("time without time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "DayOfWeek")
                        .IsUnique();

                    b.ToTable("WorkTimes", t =>
                        {
                            t.HasCheckConstraint("CK_WorkTime_DayOfWeek", "[DayOfWeek] >= 0 AND [DayOfWeek] <= 6");
                        });
                });

            modelBuilder.Entity("gozba_na_klik.Model.Entities.Address", b =>
                {
                    b.HasOne("gozba_na_klik.Model.Entities.User", "User")
                        .WithMany("Addresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("gozba_na_klik.Model.Entities.Restaurant", b =>
                {
                    b.HasOne("gozba_na_klik.Model.Entities.User", "Owner")
                        .WithMany("Restaurants")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("gozba_na_klik.Model.Entities.UserAllergen", b =>
                {
                    b.HasOne("gozba_na_klik.Model.Entities.Allergen", "Allergen")
                        .WithMany("UserAllergens")
                        .HasForeignKey("AllergenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("gozba_na_klik.Model.Entities.User", "User")
                        .WithMany("UserAllergens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Allergen");

                    b.Navigation("User");
                });

            modelBuilder.Entity("gozba_na_klik.Model.Entities.WorkTime", b =>
                {
                    b.HasOne("gozba_na_klik.Model.Entities.User", "User")
                        .WithMany("WorkTimes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("gozba_na_klik.Model.Entities.Allergen", b =>
                {
                    b.Navigation("UserAllergens");
                });

            modelBuilder.Entity("gozba_na_klik.Model.Entities.User", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Restaurants");

                    b.Navigation("UserAllergens");

                    b.Navigation("WorkTimes");
                });
#pragma warning restore 612, 618
        }
    }
}
